# Modify name if deploying multiple instances
name = "sub-box"

main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# [placement]
mode = "usb-box"

# Environment variables
# Modify these to use the correct environment variables
[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "1160301" # Change this to a secure password
JWT_SECRET = "bD80E7E04D604CE70B2B0DA940566867D75B7333" # Change this to a secure secret key
SESSION_TAG = "0"
SESSION_DURATION = "7d"
DEPLOY_TARGET = "cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "usb-box" # Change this to the name of your D1 database
database_id = "f586c92c-3490-4dfc-85b5-635c03632919" # wrangler d1 info <YOUR_DATABASE_NAME>

[observability.logs]
enabled = true

# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "prod-sub-box-next-inc-cache"
